services:
  influxdb:
    image: influxdb:2.7-alpine
    container_name: telemetria_influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=telemetria2026
      - DOCKER_INFLUXDB_INIT_ORG=telemetria_org
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetria
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=telemetria-super-secret-token-2026
    volumes:
      - influxdb-data:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:10.4.0
    container_name: telemetria_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-data:/var/lib/grafana

volumes:
  influxdb-data:
  grafana-data:
